"use strict";
// MIT. Generated by tools/ai-integration/build-browser-model.cjs; do not edit.
// Exact frozen linear model and encoder.
(function(root) {
"use strict";
// Binary/threshold encoding informed by the fixed PBAI-P6 encoder.
// Copyright (c) 2026 cultivationdata.net. MIT; see prototype/ENGINE_LICENSE.txt.
// NYAKUA-specific layout; not compatible with the source's 399-bit model.
const E = root.BaoEngine;
const Q = root.NakakamadoSearchTransition.createForEngine(E);
const ID = "NAKAKAMADO-BINARY-v1", INPUT_SIZE = 368;
function validate(s) {
  if (!s || ![0,1].includes(s.player) || !["namua","mtaji"].includes(s.phase)
    || s.winner !== null || s.reason !== "" || Q.outcome(s) !== "ongoing"
    || !Number.isSafeInteger(s.turn) || s.turn < 0) throw Error("Only ongoing v0.8.0 states are encodable");
  const pair = a => Array.isArray(a) && a.length === 2;
  const count = (n,max=64) => Number.isSafeInteger(n) && n >= 0 && n <= max;
  if (![s.pits,s.reserve,s.nyakuaReserve,s.pending,s.houseOwned].every(pair)) throw Error("State shape");
  for (let p=0;p<2;p++) {
    if (!pair(s.pits[p]) || !s.pits[p].every(r=>Array.isArray(r)&&r.length===8&&r.every(n=>count(n)))) throw Error("Pit range or shape");
    if (!count(s.reserve[p]) || !count(s.nyakuaReserve[p],1) || s.pending[p] !== 0
      || typeof s.houseOwned[p] !== "boolean") throw Error("Hand, pending or house range");
  }
  if ([...s.pits.flat(2),...s.reserve,...s.nyakuaReserve,...s.pending].reduce((a,n)=>a+n,0)!==64) throw Error("Total KETE must be 64");
  if (s.phase === "mtaji" && [...s.reserve,...s.nyakuaReserve].some(Boolean)) throw Error("MTAJI hand must be empty");
}
function placement(s,p) {return s.phase === "mtaji" ? 0 : Math.min(s.reserve[p],s.nyakuaReserve[p]?2:1)+s.nyakuaReserve[p];}
function encode(s,p=s.player) {
  validate(s); if (![0,1].includes(p)) throw Error("Perspective");
  const sides=[p,1-p], x=[];
  const bits=(n,w)=>{for(let j=0;j<w;j++)x.push((n>>>j)&1);};
  for (const side of sides) for (const row of s.pits[side]) for (const n of row) {
    bits(n,7);for(const t of [1,2,4])x.push(Number(n>=t));
  }
  for(const side of sides)bits(s.reserve[side],7);
  for(const side of sides)x.push(s.nyakuaReserve[side]);
  for(const side of sides)bits(s.pending[side],7);
  for(const side of sides)x.push(Number(s.houseOwned[side]));
  x.push(Number(s.player===p),Number(s.phase==="mtaji"));
  for(const side of sides)for(let n=0;n<=3;n++)x.push(Number(placement(s,side)===n));
  for(const side of sides)for(let n=0;n<=2;n++)x.push(Number(s.reserve[side]===n));
  if(x.length!==INPUT_SIZE)throw Error("Input size"); return x;
}
function positionKey(s) {
  validate(s); const sides=[s.player,1-s.player];
  // Normalize side names only. Do not reflect the pit indexes or fixed NYUMBA.
  // Turn is bookkeeping in this engine, retained separately by Q.stateKey.
  return JSON.stringify([E.RULE_ID,E.RULES_VERSION,sides.map(p=>s.pits[p]),
    sides.map(p=>s.reserve[p]),sides.map(p=>s.nyakuaReserve[p]),sides.map(p=>s.pending[p]),
    sides.map(p=>s.houseOwned[p]),s.phase]);
}


const MODEL_BYTES = "{\"schema\":1,\"specId\":\"NAKAKAMADO-FORMAL-LEARNING-20261005-v1\",\"inputSize\":368,\"encodingId\":\"NAKAKAMADO-BINARY-v1\",\"kind\":\"linear\",\"seed\":2026100401,\"learningFingerprint\":\"872a4690be9cd686ace800052e01b4afda5488c2cae60fb41cbc458a2958045c\",\"trainDigest\":\"1591876c038681e42299fadebf11a653b52a9872117d86323d476827d58b0b16\",\"quantizationScale\":4096,\"weights\":[17,34,56,102,0,0,0,155,60,58,60,24,14,224,-37,0,0,162,-20,34,32,63,-43,255,85,0,0,91,33,124,57,50,19,330,82,0,0,201,-107,153,57,85,74,248,201,0,0,51,-119,134,56,34,72,279,57,0,0,128,-78,87,76,25,-31,262,51,0,0,77,-35,147,60,13,-16,199,7,0,0,225,-16,108,84,86,69,128,6,0,0,-18,196,201,174,34,216,102,0,0,0,-96,152,319,216,34,269,29,0,0,0,-121,153,297,17,-36,183,47,0,0,0,16,108,229,58,58,161,45,0,0,0,-45,178,206,122,68,85,55,0,0,0,-122,119,140,129,6,85,102,0,0,0,-44,136,186,84,-15,41,103,0,0,0,32,165,144,-17,-34,-56,-102,0,0,0,-155,-60,-58,-60,-24,-14,-224,37,0,0,-162,20,-34,-32,-63,43,-255,-85,0,0,-91,-33,-124,-57,-50,-19,-330,-82,0,0,-201,107,-153,-57,-85,-74,-248,-201,0,0,-51,119,-134,-56,-34,-72,-279,-57,0,0,-128,78,-87,-76,-25,31,-262,-51,0,0,-77,35,-147,-60,-13,16,-199,-7,0,0,-225,16,-108,-84,-86,-69,-128,-6,0,0,18,-196,-201,-174,-34,-216,-102,0,0,0,96,-152,-319,-216,-34,-269,-29,0,0,0,121,-153,-297,-17,36,-183,-47,0,0,0,-16,-108,-229,-58,-58,-161,-45,0,0,0,45,-178,-206,-122,-68,-85,-55,0,0,0,122,-119,-140,-129,-6,-85,-102,0,0,0,44,-136,-186,-84,15,-41,-103,0,0,0,-32,-165,-144,11,-5,18,-10,132,0,0,-11,5,-18,10,-132,0,0,220,-220,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-83,83,2582,0,-251,213,36,3,251,-213,-36,-3,-70,-59,-234,70,59,234],\"bias\":-1291}\n";
const MODEL_SHA256 = "f74175fbaa6f2d6a82148cf5e106da7291f396b2b38cb79866dc641b2147254d";
const MODEL_ID = "NAKAKAMADO-FROZEN-LINEAR-2026100401-v1";
const m = JSON.parse(MODEL_BYTES);
function raw(x) { return x.reduce((n,v,i) => n + v*m.weights[i], m.bias); }
function createEvaluator() {
  function evaluate(s,p=s.player,check=()=>{}) {
    check(); const outcome=Q.outcome(s);
    if(outcome==='safety-stop') return 0;
    if(outcome==='normal-terminal') return s.winner===p ? 1000000 : -1000000;
    const a=raw(encode(s,p)), b=raw(encode(s,1-p)), scale=m.quantizationScale;
    const clip=n=>Math.max(-scale,Math.min(scale,n));
    check(); return Math.trunc(1024*(clip(a)-clip(b))/(2*scale)) || 0;
  }
  return Object.freeze({ID:MODEL_ID, WIN:1000000, evaluate,
    breakdown:(s,p=s.player,check)=>({evaluatorId:MODEL_ID,total:evaluate(s,p,check),outcome:Q.outcome(s)})});
}
async function verifyBytes() {
  const digest=await root.crypto.subtle.digest('SHA-256',new TextEncoder().encode(MODEL_BYTES));
  const actual=Array.from(new Uint8Array(digest),n=>n.toString(16).padStart(2,'0')).join('');
  if(actual!==MODEL_SHA256) throw Error('Frozen model digest mismatch');
}
root.NakakamadoBrowserModel=Object.freeze({MODEL_ID,MODEL_SHA256,createEvaluator,verifyBytes,encode});
}(typeof window !== 'undefined' ? window : globalThis));
